FROM frolvlad/alpine-glibc as builder
RUN apk add git go g++

RUN mkdir -p /go/src/github.com/chrislusf/
RUN git clone https://github.com/chrislusf/seaweedfs /go/src/github.com/chrislusf/seaweedfs
RUN cd /go/src/github.com/chrislusf/seaweedfs/weed && go install

FROM alpine AS final
RUN apk add fuse
LABEL author="Chris Lu"
COPY --from=builder /root/go/bin/weed /usr/bin/
COPY ./_output/seaweedfs-csi-driver /seaweedfs-csi-driver

RUN chmod +x /seaweedfs-csi-driver
ENTRYPOINT ["/seaweedfs-csi-driver"]
