{{- if and .Values.security.enabled .Values.security.create .Values.security.content (not .Values.security.existingSecret) (not .Values.security.existingConfigMap) }}
{{- if eq .Values.security.type "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-security-config
  labels:
    app: {{ template "seaweedfs-csi-driver.name" . }}
type: Opaque
stringData:
  security.toml: |
    {{- .Values.security.content | nindent 4 }}
{{- else if eq .Values.security.type "configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-security-config
  labels:
    app: {{ template "seaweedfs-csi-driver.name" . }}
data:
  security.toml: |
    {{- .Values.security.content | nindent 4 }}
{{- end }}
{{- end }}
