---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-controller-sa
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ .Values.imagePullSecrets | toYaml }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-node-sa
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ .Values.imagePullSecrets | toYaml }}
{{- end }}
