{{- if .Values.storageClassName }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClassName }}
  annotations:
    {{- if .Values.isDefaultStorageClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: {{ .Values.driverName }}
allowVolumeExpansion: true
{{- end }}
